### ISSUE TITLE
Modifying litecoin-node-status.py causes issue with cron

### ISSUE THREAD

**Issue by gotchay** [litecoin-association/LitecoinNode#17]
After deploying LitecoinNode on a fresh install of Ubuntu 14.04 the status page and litecoind work flawlessly but as soon as I make slight modifications to the litecoin-node-status.py file (editing site title etc.) cron starts throwing issues to mail that state:

Date: Wed, 23 Sep 2015 19:00:01 +0000 (UTC)
From: Cron Daemon <root@SHMD001.cs1cloud.internal>
To: root@SHMD001.cs1cloud.internal
Subject: Cron <root@SHMD001> /usr/bin/python
        /home/litecoind/scripts/litecoin-node-status.py

Traceback (most recent call last):
  File "/home/litecoind/scripts/litecoin-node-status.py", line 11, in <module>
    lcd_data = get_lcd_info.getinfo()
NameError: name 'get_lcd_info' is not defined

However, that line and everything before it has been unmodified. Replacing the .py file from the one on github doesn't fix the issue.

**Comment by losh11** [comment]
Technically you shouldn't be modifying the file which generates the CSS and HTML. You should instead modify the index.html and CSS files created (initially) using this Python script.

I can't remember exactly what directory the files are kept, since I'm on mobile, but as soon as I'm back on Desktop, I will find this for you.

If you could also post the code that you changed to using a '>' tag like this:-
> code

That should help debugging why you got these errors.

**Comment by gotchay** [comment]
You mean the files in /usr/share/nginx/html ???

Don't those files get overwritten by the script every 10 minutes? Changes to the .html file would be moot at that point right?

**Comment by losh11** [comment]
The error you referred to is to do with the IP grabbing. This is when we
use a JSON GET request to get a group of IPs and its associated locations,
and if your IP is within that block it will write that as your location.

For now, I can only think of forking our project from GitHub, and then
manually editing the Python file. After this, modify the glob-vars file and
then change the link for the Python file to your repos Python file. Then
run the project from your GitHub repo.

The long term solution which will be added soon, is an option
called 'Advanced Options'; which allows a user to import their own
custom CSS/HTML. This will probably be done by the user inputting a
location for a CSS/HTML file, which will then be extracted and then put
into a file called 'customwebdata.py' The default file for updating the
homepage should then be modified to 'customwebdata.py'.

I really don't know why the error is occurring, but I'll be trying on my
server tomorrow to replicate the issue. I'm wondering if your error is
being caused by the version of Python you are using. Are you using Python 2
or 3?

**Comment by losh11** [comment]
You can't modify any file by replacing it with a local version because most files are grabbed from GitHub and ran from there. Cloning to a local directory will not work because all commands must come from the original source, unless you modify the glob-vars file; in this file there are links and basic functions which are used throughout the project.

**Comment by gotchay** [comment]
I figured out what went wrong. By copying the script from the github page I'm leaving out the authentication to litecoind so it can scrape for info. You can close this, but looking forward to the advanced options. Thank you!
